### ISSUE TITLE
fetch PDFs

### ISSUE THREAD

**Issue by JohannesBuchner** [pcubillos/bibmanager#40]
Hi,

Can it fetch PDFs files from the journal and/or arxiv and link them as a file= entry in the bibtex? 

The old Jabref had a great extension called LocalCopy https://github.com/lehner/LocalCopy that did this marvelously. Alas, old Jabref went away.

Cheers,
Johannes

**Comment by pcubillos** [comment]
Hi,
not right now, but that's a great idea. It shouldn't be hard to implement, I'll take a look at that link.

**Comment by pcubillos** [comment]
This package seems to do the trick to fetch/maintain a database for the PDF files:
https://github.com/pkgw/bibtools

Will research how to integrate their stuff into bibmanager.

**Comment by pcubillos** [comment]
Hi @JohannesBuchner !
So, I finally managed to implement some decent PDF managing [it only took me a month of work :) ].  There are a few basic commands:
``bibm fetch``: to fetch PDF files from ADS
``bibm pdf``: to manually set/rename PDF files for the entries with files that are already in the machine
``bibm open``: to open the respective PDF file of a given entry
(All of these have auto-completion/auto-suggest to make it easier to find the bibcodes/keys)

The user can also set PDFs via the ``bibm edit`` command.

Was there anything else you had in mind that might be useful?

The updated code is in a pre-release version (v1.2.0rc1).  I wanted to get your opinion on this first.
You can take a look at the docs/examples here:
https://bibmanager.readthedocs.io/en/v1.2.0rc1/pdf.html

Best,
p

**Comment by pcubillos** [comment]
Closed with merge of #55
