### ISSUE TITLE
[Bug] Installing from PyPI will not initialize database

### ISSUE THREAD

**Issue by 1313e** [pcubillos/bibmanager#49]
After one installs `bibmanager` using `pip install bibmanager`, the `bibmanager.bib_manager.init()` function is not executed, and therefore the database is never initialized.
This will result into an error stating that `No section: 'BIBMANAGER'` whenever anything related to the command line commands is used, as it cannot find the config file.
Executing `python -c import bibmanager; bibmanager.bib_manager.init()` will fix this problem, although it will raise an error stating that the `~/.bibmanager.bm_bibliography.bib` file cannot be found (which normally was ignored in the `setup.py` file and thus does not matter).

This problem is also the one that causes the problem in #45.

**Comment by pcubillos** [comment]
Resolved by c4b2bd0
