### ISSUE TITLE
[Feature request] Setting the home/root directory manually

### ISSUE THREAD

**Issue by 1313e** [pcubillos/bibmanager#50]
I do really like using `bibmanager` for managing my BibTeX entries, but it kinda annoys me that it automatically uses `~/.bibmanager` as the directory to store all information in.
As I use several different machines, I would like to use only one database across every single one of them.
Currently, I am forced to make a softlink between `~/.bibmanager` and the actual address where the directory is stored, which is then synchronized on all of my computers.

It would be quite a bit easier if I could setup `bibmanager` manually to directly point to the actual address by using one of its command line commands, which would simply default to `~/.bibmanager` if the user does not set it.

**Comment by pcubillos** [comment]
Yeah, I have the same issue.  I'll put the database location into one of the config variables, that should allow users to put the database into a Dropbox-type of syncing folder.
Thanks.

**Comment by pcubillos** [comment]
Hi @1313e,

The database's home directory can be set by the user, so you can put it in a Dropbox folder and work across multiple machines.  Take a look at tag v1.2.0rc2:
https://pypi.org/project/bibmanager/1.2.0rc2/
https://bibmanager.readthedocs.io/en/v1.2.0rc2/

Also PDF management is now enabled (including ADS fetching).

**Comment by pcubillos** [comment]
Closed with merge of #55
