### ISSUE TITLE
import all bibtex from ADS searches

### ISSUE THREAD

**Issue by JohannesBuchner** [pcubillos/bibmanager#60]
Hi,

For systematic literature reviews, it is useful to fetch all papers matching some keywords published within some period of time, and read them all.

I imagined bibmanager could help me here, even downloading the associated PDFs. 

However, I cannot figure out how to automatically add ADS search results. I would have expected something like this:

`bibm ads-search "citation_count:[300 TO 1000000]" |bibm ads-add`

or

`bibm ads-search --add "citation_count:[300 TO 1000000]"`

However, ads-search does not seem to 

* support adding all results
* support passing search keywords by argument (non-interactive use)

ads-add does not seem to 

* support batch mode, adding multiple bibcodes

**Comment by pcubillos** [comment]
Hi,
Sorry, I didn't get initially what you wanted and then I forgot about this issue.  Now I think I understand.   I'm afraid that what you require goes beyond the core design of the package, however, you can accomplish that through the API.  Here's a couple Python scripts that do the query-add-all (and optionally fetch PDFs), and another one that does only the PDF fetch from a given bibtex file.   Is this more-or-less what you were looking for?

```python
import requests
import json

import bibmanager.bib_manager as bm
import bibmanager.ads_manager as am
import bibmanager.pdf_manager as pm
import bibmanager.config_manager as cm


def ads_add_all(query, bibtex_file, fetch=False):
    """
    Store all entries found from an ADS query into a bibtex file.
    If fetch is True, fetch all (available) PDFs into the current folder.

    Example
    --------
    >>> query = 'author:"Buchner" property:refereed'
    >>> bibtex_file = 'ads_search.bib'
    >>> ads_add_all(query, bibtex_file)
    """
    token = cm.get('ads_token')

    results, nmatch = am.search(query, cache_rows=5000)
    bibcodes = [result['bibcode'] for result in results]

    max_size = 2000
    bibcode_chunks = [
        bibcodes[i:i+max_size] for i in range(0,len(bibcodes), max_size)]
    results = ''
    for bc_chunk in bibcode_chunks:
        r = requests.post(
            "https://api.adsabs.harvard.edu/v1/export/bibtex",
            headers={"Authorization": f'Bearer {token}', "Content-type": "application/json"},
            data=json.dumps({"bibcode":bc_chunk}))
        resp = r.json()
        results += resp["export"]

    with open(bibtex_file, 'w') as f:
        f.write(results)

    if fetch:
        for bibcode in bibcodes:
            pm.fetch(bibcode)


def fetch_all(bibtex_file):
    """
    Fetch all PDFs articles of entries found in given bibtex file into the current folder.
    """
    bibs = bm.loadfile(bibtex_file)
    # Need to update, since PDF queries fail for outdated ADS bibcodes:
    ubibs = am.update(update_keys=True, base=bibs)
    bibcodes = [bib.bibcode for bib in ubibs if bib.bibcode is not None]

    for bibcode in bibcodes:
        pm.fetch(bibcode)
```

**Comment by JohannesBuchner** [comment]
Thanks, that looks useful.

Btw, for fetching many ads bibtex entries, you can do it in a single request like so, which pre-fetches the bibcode field:

```
import ads
bibcodes = [p.bibcode for p in ads.SearchQuery(q=query, fl=['bibcode'])
```

I also found it useful to install a requests cache on start-up, to avoid hitting the rate limit when debugging and asking for the same data again and again. Here is a 1h cache:

```
import requests_cache
requests_cache.install_cache('demo_cache', allowable_methods=('GET', 'POST'), expire_after=3600)

import requests
import ads
# do stuff
```

**Comment by pcubillos** [comment]
Ahh, cool!  Thanks for the tips.  I'll close this issue then.
Thanks.
