### ISSUE TITLE
subfiles

### ISSUE THREAD

**Issue by AaronDavidSchneider** [pcubillos/bibmanager#61]
Hallo,

thanks for this awesome project. Especially in combination with the ads it seems to be a very helpful tool!
Do you think it would be easily possible to include subfiles in the latex compilation?
I am just writing my masterthesis and would love to use it. However as my thesis will be longer then a few pages its hopeless to put all text into a single tex file.

**Comment by pcubillos** [comment]
Hi Aaron,
I have a tweak that makes the code to look recursively into \input{} calls within the .tex file.
Would this fix your issue?

If so, I'll clean it up and upload the patch.

**Comment by AaronDavidSchneider** [comment]
hey @pcubillos, that would be awesome!

**Comment by AaronDavidSchneider** [comment]
I think it might be also possible to look recursivley into \include, \import (standalone package) or \subfile (subfiles package) (see: https://de.overleaf.com/learn/latex/Multi-file_LaTeX_projects).

Would that be an overhead? At least \subfile and \include have the same syntax as \input (not sure about standalone)
What do you think?

**Comment by pcubillos** [comment]
Yeah, that's a good idea! I got  the \subfile and \include calls caught as well.  Do you think you'll need \import too right now?

**Comment by AaronDavidSchneider** [comment]
No I never used \import

**Comment by pcubillos** [comment]
Hi Aaron,
OK, I updated the code.  Now the content in calls to \incude, \input, and \subfile should be accounted when parsing the citations and compiling.

Good luck wrapping up your thesis!
