### ISSUE TITLE
protocol of pickle is not compatible between Python 3.6/3.7 and 3.8

### ISSUE THREAD

**Issue by monodera** [pcubillos/bibmanager#63]
Bibmanager sets the protocol of pickle as `pickle.HIGHEST_PROTOCOL` and it is `4` for Python version <=3.7, while it is `5` for Python 3.8 (https://docs.python.org/3/library/pickle.html#data-stream-format).  Because of this, the bib database created with Python 3.8 does not work if bibmanager is used in an environment using Python 3.6 or 3.7.  In fact, I got the following error.

```$ bibm search
Traceback (most recent call last):
  File "/Users/monodera/anaconda3/envs/astroconda/bin/bibm", line 8, in <module>
    sys.exit(main())
  File "/Users/monodera/anaconda3/envs/astroconda/lib/python3.6/site-packages/bibmanager/__main__.py", line 1074, in main
    pickle_ver = bm.get_version()
  File "/Users/monodera/anaconda3/envs/astroconda/lib/python3.6/site-packages/bibmanager/bib_manager/bib_manager.py", line 693, in get_version
    dummy = pickle.load(handle)
ValueError: unsupported pickle protocol: 5
```

Is there a way to recover the database for the latter environment (Python 3.6 or 3.7)? 

Additionally, as the protocol `4` is common among the supported Python versions, is there any major problems if the protocol is set as `4` explicitly?

**Comment by pcubillos** [comment]
Hmm, yeah, I see. 3.8 added the protocol level 5.
Yes, I think fixing the protocol at 4 would be the best to preserve the compatibility between 3.6--3.8.

Thanks for letting me know! I'll fix it soon.

**Comment by pcubillos** [comment]
OK, I updated the code, now the protocol is set to 4, regardless of the Python version.
Thanks a lot for the report!
