### ISSUE TITLE
Problem merging .bib with single line entries

### ISSUE THREAD

**Issue by AndresErnestoGuzman** [pcubillos/bibmanager#66]
Hola Patricio! 

Es Andrés Guzmán, estaba probando este tremendo software q hiciste. La mansa pega.

Tengo mi archivo bibliografia.bib y le puse 
`> bibm merge ~/Library/texmf/bibtex/bib/bibliografia.bib`
`Merged 60 new entries.`
`Merged BibTeX file '/Users/andres/Library/texmf/bibtex/bib/bibliografia.bib' into bibmanager database.`

O sea me agarró 60, pero tengo claramente más
`> grep -c ARTICLE ~/Library/texmf/bibtex/bib/bibliografia.bib`
`928`

Creo que el problema es que sólo pescó las que están escritas así

>  \@ARTICLE{Adams1985ApJ,
>        author = {{Adams}, F.~C. and {Shu}, F.~H.},
>         title = "{Infrared emission from protostars.}",
>       journal = {\apj},
>      keywords = {Infrared Stars, Pre-Main Sequence Stars, Protostars, Stellar Radiation, Near Infrared Radiation, Optical Thickness, Radiative Transfer, Ray Tracing, Spectral Energy Distribution, Stellar Envelopes, Stellar Temperature, Temperature Profiles, Astrophysics},
>          year = 1985,
>         month = sep,
>        volume = {296},
>         pages = {655-669},
>           doi = {10.1086/163483},
>        adsurl = {https://ui.adsabs.harvard.edu/abs/1985ApJ...296..655A},
>       adsnote = {Provided by the SAO/NASA Astrophysics Data System}
> }

Pero tengo muchas más escritas en una misma línea, así

> \@ARTICLE{Adams1991ApJ,    author = {{Adams}, F.~C.},     title = "{Asymptotic theory for the spatial distribution of protostellar emission}",   journal = {\apj},  keywords = {ASYMPTOTIC METHODS, EMISSION SPECTRA, PROTOSTARS, SPATIAL DISTRIBUTION, STAR FORMATION, COMPUTATIONAL ASTROPHYSICS, DENSITY DISTRIBUTION, PRE-MAIN SEQUENCE STARS, STELLAR ENVELOPES, STELLAR LUMINOSITY, TEMPERATURE DISTRIBUTION},      year = 1991,     month = dec,    volume = 382,     pages = {544-554},       doi = {10.1086/170741},    adsurl = {http://adsabs.harvard.edu/abs/1991ApJ...382..544A},   adsnote = {Provided by the SAO/NASA Astrophysics Data System} }

Efectivamente, cuando cuanto las que están escritas con "newlines" separando las entradas de bibtex
`> grep -cP '^\s*@[^,]+,\s*$' ~/Library/texmf/bibtex/bib/bibliografia.bib`
`60`

son justo las 60 que considera.

¿Es esto un comportamiento esperado del programa, o pensarías en arreglarlo? Bibtex reconoce las referencias puestas en una sola línea como válidas.

Saludos!

**Comment by pcubillos** [comment]
Hola, buenas!
Ahh, era un error en el programa.  Cuando, leía el archivo el código cuenta la cantidad de parentesis abiertos-cerrados en cada linea, como en este caso toda la info estaba en una sola linea, el código se saltaba la linea. Ya lo arreglé y subí un parche a pypi/github (ver 1.2.5).

Saludos!
