### ISSUE TITLE
User-defined tags when adding and searching for entries

### ISSUE THREAD

**Issue by gmduvvuri** [pcubillos/bibmanager#75]
I currently annotate my hard copies of papers with personally defined tags, similar to the Unified Astronomy Thesaurus but more flexible because I can write down any tag I want, and keep track of which papers are associated with which tags by writing them down in a notebook. This is very useful when I want to review the literature on a particular topic, but of course not ideal because I do not want to print every paper I read.

Is it possible to add user-defined tags along with the citation key when adding entries, and to later incorporate these tags like ADS keywords during a bibm search?

**Comment by pcubillos** [comment]
Hi!
Hmm, no, sorry, the current code does not have tags.  But in principle, I think it's possible to implement (and I think it's a good idea!).  I'll look elsewhere to see how it is made and will think about it.  Thanks!

**Comment by AaronDavidSchneider** [comment]
My vision would be to change the signature of `bibm ads-add` to
`bibm ads-add [ads-key] [bibkey] [tag1] [tag2] [...]`

When using `bibm browse` I would envision to have a key (e.g. `t`) that would let me type out a tag (e.g. `GCM`) and filter all `bibm browse` results by this specific tag.

These tags could also be displayed directly next to the `bibm browse` results.

There could also be an additional cli function (`bibm tag`) that works similar to `bibm pdf` which adds labels after an entry has been made.

**Comment by gmduvvuri** [comment]
Thanks a lot for adding this, it works exactly like I wanted.
