### ISSUE TITLE
skip / flag problem bib entries during merge

### ISSUE THREAD

**Issue by rhaynes74** [pcubillos/bibmanager#77]
Hi folks, I have a rather large .bib file with all my references (approx 2200).  Not surprisingly a certain percentage have "problems" - some missing entries (missing publisher etc), it is great if they are flagged for future updates but it would be great if I was still able to continue with the merge.  Currently bibmanager quits when it encounters such an entry.

**Comment by pcubillos** [comment]
Hi, yeah, that's a good idea!
I'm thinking putting the 'problematic' ones into a separate file.
and it should be easy to correct.

Thanks for the feedback!, I'll take a look at this

**Comment by rhaynes74** [comment]
That would be fantastic!

**Comment by pcubillos** [comment]
Dear Ronald,
I have just uploaded the code. It should now not break when the entries have no author, titles, or year fields.  In fact, the code should not break even if there are some small format issues.  It will rather throw a warning and continue executing.  This mimics the behavior of the ``bibtex'' command.

Thank you for raising these issues! Now the code is much more flexible!
I hope it's not the case but, please let me know if you are still seeing issues.
Regards.

PS: I also recently updated a short video tutorial walking through the features added in version 1.3: https://bibmanager.readthedocs.io/en/latest/
PS2: If you end up using this tool for your research, please consider [citing](https://bibmanager.readthedocs.io/en/latest/#be-kind) it in the acknowledgments. I would really appreciate that.

**Comment by rhaynes74** [comment]
Many thanks!  I will take a good look now!

**Comment by rhaynes74** [comment]
Hi - could you tell me when the newest version will be available via pip3 install?

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by pcubillos** [comment]
Hi, it should have been updated since Saturday, have you tried with the ``--upgrade`` argument?
```
pip3 install --upgrade bibmanager
```

**Comment by rhaynes74** [comment]
Great - thanks for your attention!

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.
