### ISSUE TITLE
issue with importing bibtex entry for book

### ISSUE THREAD

**Issue by rhaynes74** [pcubillos/bibmanager#78]
Hi folks, bibm merge balks at merging a .bib entry for a book if it doesn't have an author.  In my case it has an editor and the bibtex documentation says that the required field is an author OR and editor. 

Best,
R Haynes

**Comment by pcubillos** [comment]
Hi, yes, that's a known 'feature'. Originally, I designed the code to request having author, year, and title (to do all the indexing, sorting, etc.). Actually I couldn't conceive entries could not have an author entry (my bad!).
I will sort this out along with #77 

Sorry about that!

**Comment by rhaynes74** [comment]
Thanks!

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by rhaynes74** [comment]
> Hi, yes, that's a known 'feature'. Originally, I designed the code to request having author, year, and title (to do all the indexing, sorting, etc.). Actually I couldn't conceive entries could not have an author entry (my bad!).
> I will sort this out along with #77
> 
> Sorry about that!

Hi everyone - is there an estimated time frame for this fix?   Write now it stops me from using bibmanager.
Thanks!
RH

**Comment by pcubillos** [comment]
Hi,
I'm half way there. I hoped to put more time on this during the new year's break but didn't. The update gets fiddly since most of the indexing depends on these variables, but I think I can have a solution over the week.  Thanks for the patience!

**Comment by rhaynes74** [comment]
Thanks for the update, looking forward to trying it out!

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.
