### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by rhaynes74** [pcubillos/bibmanager#83]
Hi - I hope things are well.  I wanted to try the newest version, so I cloned the repo from github, unfortunately I get an error:

python setup.py develop
  File "setup.py", line 57
    """
      ^
SyntaxError: invalid syntax

Is it possible that I am missing something?

**Comment by pcubillos** [comment]
Hi, I think you are running this in a python version < 3.6.

**Comment by rhaynes74** [comment]
Quite likely! python management is always such a mess!

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by pcubillos** [comment]
OK, glad that that fixed the issue!
I know python versioning can get confusing.  You could take a look at the FAQs where I wrote a tip to avoid dealing with virtual environments once you have installed the package:

https://bibmanager.readthedocs.io/en/latest/faq.html#i-installed-bibmanager-while-being-in-a-virtual-environment-but-i-don-t-want-to-start-the-virtual-env-every-time-i-want-to-use-bibm
